/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u10392310120
 */
public class jDlgWhfAntiguidades extends javax.swing.JDialog {

    /**
     * Creates new form jDlgWhfAntiguidades
     */
    public jDlgWhfAntiguidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);    
        setTitle("Cadastro de Antiguidades");
        habilitar(false);

    }
    
    
public void habilitar(boolean valor) {
    jTxtWhfCódigo.setEnabled(valor);
    jTxtWhfNome.setEnabled(valor);
    jTxtWhfFornecedor.setEnabled(valor);
    jTxtWhfDescrição.setEnabled(valor);
    jTxtWhfAnoOrigem.setEnabled(valor);
    jCboWhfCategoria.setEnabled(valor);
    jTxtWhfQuantidade.setEnabled(valor);
    jFmtWhfValor.setEnabled(valor);
    jChbWhfAtivo.setEnabled(valor);
    jBtnWhfConfirmar.setEnabled(valor);
    jBtnWhfCancelar.setEnabled(valor);
    jBtnWhfIncluir.setEnabled(!valor);
    jBtnWhfAlterar.setEnabled(!valor);
    jBtnWhfExcluir.setEnabled(!valor);
    jBtnWhfPesquisar.setEnabled(!valor);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtWhfCódigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtWhfNome = new javax.swing.JTextField();
        jTxtWhfDescrição = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtWhfAnoOrigem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCboWhfCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtWhfQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtWhfFornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmtWhfValor = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jChbWhfAtivo = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jBtnWhfPesquisar = new javax.swing.JButton();
        jBtnWhfIncluir = new javax.swing.JButton();
        jBtnWhfAlterar = new javax.swing.JButton();
        jBtnWhfConfirmar = new javax.swing.JButton();
        jBtnWhfExcluir = new javax.swing.JButton();
        jBtnWhfCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Descrição");

        jLabel4.setText("Ano Origem");

        jCboWhfCategoria.setEditable(true);
        jCboWhfCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobiliário Antigo", "Objetos Pessoais", "Artes e Decoração", "Colecionáveis" }));
        jCboWhfCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboWhfCategoriaActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria");

        jLabel6.setText("Quantidade");

        jLabel7.setText("Fornecedor");

        jLabel8.setText("Valor");

        jChbWhfAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbWhfAtivoActionPerformed(evt);
            }
        });

        jLabel9.setText("Ativo");

        jBtnWhfPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnWhfPesquisar.setText("Pesquisar");
        jBtnWhfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfPesquisarActionPerformed(evt);
            }
        });

        jBtnWhfIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnWhfIncluir.setText("Incluir");
        jBtnWhfIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfIncluirActionPerformed(evt);
            }
        });

        jBtnWhfAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnWhfAlterar.setText("Alterar");
        jBtnWhfAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfAlterarActionPerformed(evt);
            }
        });

        jBtnWhfConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnWhfConfirmar.setText("Confirmar");
        jBtnWhfConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfConfirmarActionPerformed(evt);
            }
        });

        jBtnWhfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnWhfExcluir.setText("Excluir");
        jBtnWhfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfExcluirActionPerformed(evt);
            }
        });

        jBtnWhfCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnWhfCancelar.setText("Cancelar");
        jBtnWhfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jCboWhfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtWhfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtWhfCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtWhfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtWhfDescrição, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtWhfFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtWhfAnoOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jFmtWhfValor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnWhfIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnWhfAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnWhfExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnWhfConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnWhfCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnWhfPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jChbWhfAtivo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtWhfCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWhfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWhfDescrição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWhfAnoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboWhfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWhfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWhfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtWhfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChbWhfAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfCancelar)
                        .addComponent(jBtnWhfPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfExcluir)
                        .addComponent(jBtnWhfConfirmar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfIncluir)
                        .addComponent(jBtnWhfAlterar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChbWhfAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbWhfAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbWhfAtivoActionPerformed

    private void jBtnWhfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfPesquisarActionPerformed
        JOptionPane.showInputDialog(null, "Entre com a chave primária");          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnWhfPesquisarActionPerformed

    private void jBtnWhfIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfIncluirActionPerformed
        //habilitar();
        habilitar(true);
    }//GEN-LAST:event_jBtnWhfIncluirActionPerformed

    private void jBtnWhfAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfAlterarActionPerformed
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnWhfAlterarActionPerformed

    private void jBtnWhfConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfConfirmarActionPerformed
        habilitar(!rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnWhfConfirmarActionPerformed

    private void jBtnWhfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfExcluirActionPerformed
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão",
            "Selecione uma opção",JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnWhfExcluirActionPerformed

    private void jBtnWhfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfCancelarActionPerformed
        //desabilitar();
        habilitar(false);
    }//GEN-LAST:event_jBtnWhfCancelarActionPerformed

    private void jCboWhfCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboWhfCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboWhfCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlgWhfAntiguidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlgWhfAntiguidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlgWhfAntiguidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlgWhfAntiguidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlgWhfAntiguidades dialog = new jDlgWhfAntiguidades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnWhfAlterar;
    private javax.swing.JButton jBtnWhfCancelar;
    private javax.swing.JButton jBtnWhfConfirmar;
    private javax.swing.JButton jBtnWhfExcluir;
    private javax.swing.JButton jBtnWhfIncluir;
    private javax.swing.JButton jBtnWhfPesquisar;
    private javax.swing.JComboBox<String> jCboWhfCategoria;
    private javax.swing.JCheckBox jChbWhfAtivo;
    private javax.swing.JFormattedTextField jFmtWhfValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtWhfAnoOrigem;
    private javax.swing.JTextField jTxtWhfCódigo;
    private javax.swing.JTextField jTxtWhfDescrição;
    private javax.swing.JTextField jTxtWhfFornecedor;
    private javax.swing.JTextField jTxtWhfNome;
    private javax.swing.JTextField jTxtWhfQuantidade;
    // End of variables declaration//GEN-END:variables
}
