/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u10392310120
 */
public class JDlgWhfVendedores extends javax.swing.JDialog {

    /**
     * Creates new form JDlgWhfVendedores
     */
    public JDlgWhfVendedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);    
        setTitle("Cadastro de Vendedores");
        habilitar(false);
    }
 
    public void habilitar(boolean valor){
    jTxtWhfNome.setEnabled(valor);
    jFmtWhfCpf.setEnabled(valor);
    jCboWhfNível.setEnabled(valor);
    jTxtWhfCodigo.setEnabled(valor);
    jFmtWhfEmail.setEnabled(valor);
    jChbWhfAtivo.setEnabled(valor);
    jFmtWhfTelefone.setEnabled(valor);
    jBtnWhfConfirmar.setEnabled(valor);
    jBtnWhfCancelar.setEnabled(valor);
    jBtnWhfIncluir.setEnabled(!valor);
    jBtnWhfAlterar.setEnabled(!valor);
    jBtnWhfExcluir.setEnabled(!valor);
    jBtnWhfPesquisar.setEnabled(!valor);


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtWhfNome = new javax.swing.JTextField();
        jFmtWhfCpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFmtWhfEmail = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmtWhfTelefone = new javax.swing.JFormattedTextField();
        jChbWhfAtivo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtWhfCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCboWhfNível = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jBtnWhfPesquisar = new javax.swing.JButton();
        jBtnWhfIncluir = new javax.swing.JButton();
        jBtnWhfAlterar = new javax.swing.JButton();
        jBtnWhfConfirmar = new javax.swing.JButton();
        jBtnWhfExcluir = new javax.swing.JButton();
        jBtnWhfCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jFmtWhfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtWhfCpfActionPerformed(evt);
            }
        });

        jLabel2.setText("Cpf");

        jLabel3.setText("Email");

        jLabel4.setText("Telefone");

        jLabel5.setText("Nivel");

        jLabel7.setText("Código");

        jCboWhfNível.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Vendedor Junior", "Vendedor Pleno", "Vendedor Sênior" }));

        jLabel8.setText("Ativo");

        jBtnWhfPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnWhfPesquisar.setText("Pesquisar");
        jBtnWhfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfPesquisarActionPerformed(evt);
            }
        });

        jBtnWhfIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnWhfIncluir.setText("Incluir");
        jBtnWhfIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfIncluirActionPerformed(evt);
            }
        });

        jBtnWhfAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnWhfAlterar.setText("Alterar");
        jBtnWhfAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfAlterarActionPerformed(evt);
            }
        });

        jBtnWhfConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnWhfConfirmar.setText("Confirmar");
        jBtnWhfConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfConfirmarActionPerformed(evt);
            }
        });

        jBtnWhfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnWhfExcluir.setText("Excluir");
        jBtnWhfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfExcluirActionPerformed(evt);
            }
        });

        jBtnWhfCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnWhfCancelar.setText("Cancelar");
        jBtnWhfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTxtWhfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(jFmtWhfEmail))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFmtWhfTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(jTxtWhfNome))
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jFmtWhfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jCboWhfNível, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jChbWhfAtivo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnWhfIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnWhfAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnWhfExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnWhfConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnWhfCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnWhfPesquisar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtWhfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtWhfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtWhfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboWhfNível, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFmtWhfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtWhfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jChbWhfAtivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfCancelar)
                        .addComponent(jBtnWhfPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfExcluir)
                        .addComponent(jBtnWhfConfirmar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfIncluir)
                        .addComponent(jBtnWhfAlterar)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmtWhfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtWhfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtWhfCpfActionPerformed

    private void jBtnWhfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfPesquisarActionPerformed
        JOptionPane.showInputDialog(null, "Entre com a chave primária");          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnWhfPesquisarActionPerformed

    private void jBtnWhfIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfIncluirActionPerformed
        //habilitar();
        habilitar(true);
    }//GEN-LAST:event_jBtnWhfIncluirActionPerformed

    private void jBtnWhfAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfAlterarActionPerformed
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnWhfAlterarActionPerformed

    private void jBtnWhfConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfConfirmarActionPerformed
        habilitar(!rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnWhfConfirmarActionPerformed

    private void jBtnWhfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfExcluirActionPerformed
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão",
            "Selecione uma opção",JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnWhfExcluirActionPerformed

    private void jBtnWhfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfCancelarActionPerformed
        //desabilitar();
        habilitar(false);
    }//GEN-LAST:event_jBtnWhfCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgWhfVendedores dialog = new JDlgWhfVendedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnWhfAlterar;
    private javax.swing.JButton jBtnWhfCancelar;
    private javax.swing.JButton jBtnWhfConfirmar;
    private javax.swing.JButton jBtnWhfExcluir;
    private javax.swing.JButton jBtnWhfIncluir;
    private javax.swing.JButton jBtnWhfPesquisar;
    private javax.swing.JComboBox<String> jCboWhfNível;
    private javax.swing.JCheckBox jChbWhfAtivo;
    private javax.swing.JFormattedTextField jFmtWhfCpf;
    private javax.swing.JFormattedTextField jFmtWhfEmail;
    private javax.swing.JFormattedTextField jFmtWhfTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtWhfCodigo;
    private javax.swing.JTextField jTxtWhfNome;
    // End of variables declaration//GEN-END:variables
}
