/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u10392310120 
 */
public class JDlgWhfUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgWhfUsuarios
     */public JDlgWhfUsuarios(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setTitle("Cadastro de Usuários");
    setLocationRelativeTo(null);
    habilitar(false);
} // <-- FECHOU AQUI

public void habilitar(boolean valor) {
    jTxtWhfCodigo.setEnabled(valor);
    jTxtWhfNome.setEnabled(valor);
    jFmtWhfCpf.setEnabled(valor);
    jFmtWhfDataNascimento.setEnabled(valor);
    jCboWhfNivel.setEnabled(valor);
    jPwfWhfSenha.setEnabled(valor);
    jChbWhfAtivo.setEnabled(valor);
    jFmtWhfEmail.setEnabled(valor);
    jBtnWhfConfirmar.setEnabled(valor);
    jBtnWhfCancelar.setEnabled(valor);
    jBtnWhfIncluir.setEnabled(!valor);
    jBtnWhfAlterar.setEnabled(!valor);
    jBtnWhfExcluir.setEnabled(!valor);
    jBtnWhfPesquisar.setEnabled(!valor);
}

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtWhfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtWhfCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtWhfDataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCboWhfNivel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPwfWhfSenha = new javax.swing.JPasswordField();
        jChbWhfAtivo = new javax.swing.JCheckBox();
        jBtnWhfIncluir = new javax.swing.JButton();
        jBtnWhfAlterar = new javax.swing.JButton();
        jBtnWhfConfirmar = new javax.swing.JButton();
        jBtnWhfExcluir = new javax.swing.JButton();
        jBtnWhfCancelar = new javax.swing.JButton();
        jBtnWhfPesquisar = new javax.swing.JButton();
        jTxtWhfCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFmtWhfEmail = new javax.swing.JFormattedTextField();

        jButton5.setText("jButton1");

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jTxtWhfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWhfNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        jLabel5.setText("Data de Nascimento");

        jLabel6.setText("Nível");

        jCboWhfNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboWhfNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboWhfNivelActionPerformed(evt);
            }
        });

        jLabel7.setText("Senha");

        jChbWhfAtivo.setText("Ativo");
        jChbWhfAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbWhfAtivoActionPerformed(evt);
            }
        });

        jBtnWhfIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnWhfIncluir.setText("Incluir");
        jBtnWhfIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfIncluirActionPerformed(evt);
            }
        });

        jBtnWhfAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnWhfAlterar.setText("Alterar");
        jBtnWhfAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfAlterarActionPerformed(evt);
            }
        });

        jBtnWhfConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnWhfConfirmar.setText("Confirmar");
        jBtnWhfConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfConfirmarActionPerformed(evt);
            }
        });

        jBtnWhfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnWhfExcluir.setText("Excluir");
        jBtnWhfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfExcluirActionPerformed(evt);
            }
        });

        jBtnWhfCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnWhfCancelar.setText("Cancelar");
        jBtnWhfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfCancelarActionPerformed(evt);
            }
        });

        jBtnWhfPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnWhfPesquisar.setText("Pesquisar");
        jBtnWhfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWhfPesquisarActionPerformed(evt);
            }
        });

        jTxtWhfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWhfCodigoActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCboWhfNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(134, 134, 134)
                        .addComponent(jChbWhfAtivo)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtWhfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtWhfNome)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(117, 117, 117)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnWhfIncluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnWhfAlterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnWhfExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnWhfConfirmar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnWhfCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnWhfPesquisar))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFmtWhfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jFmtWhfCpf))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jFmtWhfDataNascimento))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPwfWhfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtWhfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWhfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtWhfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtWhfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtWhfEmail)
                    .addComponent(jPwfWhfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChbWhfAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboWhfNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfCancelar)
                        .addComponent(jBtnWhfPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfExcluir)
                        .addComponent(jBtnWhfConfirmar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnWhfIncluir)
                        .addComponent(jBtnWhfAlterar)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtWhfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWhfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWhfNomeActionPerformed

    private void jCboWhfNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboWhfNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboWhfNivelActionPerformed

    private void jBtnWhfIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfIncluirActionPerformed
        //habilitar();
        habilitar(true);
    }//GEN-LAST:event_jBtnWhfIncluirActionPerformed

    private void jBtnWhfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfCancelarActionPerformed
        //desabilitar();
        habilitar(false);
    }//GEN-LAST:event_jBtnWhfCancelarActionPerformed

    private void jBtnWhfAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfAlterarActionPerformed
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnWhfAlterarActionPerformed

    private void jBtnWhfConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfConfirmarActionPerformed
        habilitar(!rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnWhfConfirmarActionPerformed

    private void jBtnWhfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfExcluirActionPerformed
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão",
                "Selecione uma opção",JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnWhfExcluirActionPerformed

    private void jBtnWhfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWhfPesquisarActionPerformed
        JOptionPane.showInputDialog(null, "Entre com a chave primária");          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnWhfPesquisarActionPerformed

    private void jChbWhfAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbWhfAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbWhfAtivoActionPerformed

    private void jTxtWhfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWhfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWhfCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgWhfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgWhfUsuarios dialog = new JDlgWhfUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnWhfAlterar;
    private javax.swing.JButton jBtnWhfCancelar;
    private javax.swing.JButton jBtnWhfConfirmar;
    private javax.swing.JButton jBtnWhfExcluir;
    private javax.swing.JButton jBtnWhfIncluir;
    private javax.swing.JButton jBtnWhfPesquisar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCboWhfNivel;
    private javax.swing.JCheckBox jChbWhfAtivo;
    private javax.swing.JFormattedTextField jFmtWhfCpf;
    private javax.swing.JFormattedTextField jFmtWhfDataNascimento;
    private javax.swing.JFormattedTextField jFmtWhfEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPwfWhfSenha;
    private javax.swing.JTextField jTxtWhfCodigo;
    private javax.swing.JTextField jTxtWhfNome;
    // End of variables declaration//GEN-END:variables
}
